=== Libavsky/Study/XMLproject/src/main/java/3/XXXML/movies.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/typy" xmlns:typy="http://www.example.org/typy" elementFormDefault="qualified" >

    <xs:element name="filmy" type="typy:filmyType" />
    <xs:complexType name="autorzyType">
        <xs:sequence>
            <xs:element type="xs:string" name="autor" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="wersjaType">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2"/>
            <xs:maxExclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="metadaneType">
        <xs:sequence>
            <xs:element type="typy:autorzyType" name="autorzy" />
            <xs:element type="typy:wersjaType" name="wersja"/>
            <xs:element type="xs:string" name="opis"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="aktorType">
        <xs:sequence>
            <xs:element name="imię">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="1000"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="nazwisko">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="1000"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:anyURI" name="filmweb" use="optional"/>
    </xs:complexType>
    <xs:complexType name="aktorzyType">
        <xs:sequence>
            <xs:element type="typy:aktorType" name="aktor" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="gatunekType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="GATUNEK" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Science-Fiction" />
                            <xs:enumeration value="Przygodowy" />
                            <xs:enumeration value="Dramat" />
                            <xs:enumeration value="Komedia" />
                            <xs:enumeration value="Kryminał" />
                            <xs:enumeration value="Fantasy" />
                            <xs:enumeration value="Horror" />
                            <xs:enumeration value="Obyczajowy" />
                            <xs:enumeration value="Dokument" />
                            <xs:enumeration value="Thriller" />
                            <xs:enumeration value="Quentin_Tarantino" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="wartość">
        <xs:restriction base="xs:long">
            <xs:maxExclusive value="1000000000000"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="box_officeType">
        <xs:simpleContent>
            <xs:extension base="typy:wartość">
                <xs:attribute name="waluta" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Funtów" />
                            <xs:enumeration value="Euro" />
                            <xs:enumeration value="Dolarów" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="ograniczenie_wiekoweType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="od_lat" use="required">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="bez_ograniczeń" />
                            <xs:enumeration value="od_trzynastu_lat" />
                            <xs:enumeration value="dla_dorosłych" />
                            <xs:enumeration value="od_szesnastu_lat" />
                            <xs:enumeration value="od_siedmiu_lat" />
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="filmType">
        <xs:sequence>
            <xs:element name="tytuł">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="1000"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="reżyser" maxOccurs="unbounded" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="1000"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:date" name="data_premiery"/>
            <xs:element type="typy:aktorzyType" name="aktorzy"/>
            <xs:element type="typy:gatunekType" name="gatunek" />
            <xs:element type="typy:box_officeType" name="box_office" minOccurs="0" />
            <xs:element type="typy:ograniczenie_wiekoweType" name="ograniczenie_wiekowe" />
        </xs:sequence>
        <xs:attribute type="xs:IDREF" name="studio" use="required"/>
    </xs:complexType>
    <xs:complexType name="studioType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="identyfikator" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="studiaType">
        <xs:sequence>
            <xs:element type="typy:studioType" name="studio" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="filmyType">
        <xs:sequence>
            <xs:element type="typy:metadaneType" name="metadane"/>
            <xs:element type="typy:filmType" name="film" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element type="typy:studiaType" name="studia"/>
        </xs:sequence>
    </xs:complexType>
  

  
</xs:schema>

=== Libavsky/Study/XMLproject/src/main/java/XXXML/filmy.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="moviesStylesheet.css"?>



<filmy xmlns="http://www.example.org/typy" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/typy movies.xsd">
    <metadane>
        <autorzy>
        <autor>Piotr Rokicki</autor>
        <autor>Filip Łuczak</autor>
        </autorzy>
        <wersja>2.0</wersja>
        <opis>Ranking filmów kinowych według serwisu Filmweb</opis>
    </metadane>
    <film studio = "twentieth">
        <tytuł>Skazani na Shawshank</tytuł>
        <reżyser>Frank Darabont</reżyser>
        <data_premiery>1995-04-16</data_premiery>
        <aktorzy>
            <aktor filmweb="http://www.filmweb.pl/person/Tim.Robbins">
                <imię>Tim</imię>
                <nazwisko>Robbibs</nazwisko>
            </aktor>
            <aktor filmweb="http://www.filmweb.pl/person/Morgan.Freeman">
                <imię>Morgan</imię>
                <nazwisko>Freeman</nazwisko>
            </aktor>
            <aktor>
                <imię>Bob</imię>
                <nazwisko>Gunton</nazwisko>
            </aktor>
        </aktorzy>
        <gatunek GATUNEK="Dramat"/>
        <box_office waluta="Dolarów">59841469</box_office>
        <ograniczenie_wiekowe od_lat="od_szesnastu_lat"/>
    </film>
    <film studio = "twentieth">
        <tytuł>Nietykalni</tytuł>
        <reżyser>Olivier Nakache</reżyser>
        <reżyser>Eric Toledano</reżyser>
        <data_premiery>2012-04-13</data_premiery>
        <aktorzy>
            <aktor>
                <imię>Francois</imię>
                <nazwisko>Cluzet</nazwisko>
            </aktor>
            <aktor>
                <imię>Omar</imię>
                <nazwisko>Sy</nazwisko>
            </aktor>
        </aktorzy>
        <gatunek GATUNEK="Komedia"/>
        <box_office waluta="Dolarów">426588510</box_office>
        <ograniczenie_wiekowe od_lat="od_trzynastu_lat"/>
    </film>
    <film studio = "twentieth">
        <tytuł>Zielona mila</tytuł>
        <reżyser>Frank Darabont</reżyser>
        <data_premiery>2000-03-24</data_premiery>
        <aktorzy>
            <aktor>
                <imię>Tom</imię>
                <nazwisko>Hanks</nazwisko>
            </aktor>
            <aktor>
                <imię>David</imię>
                <nazwisko>Morse</nazwisko>
            </aktor>
            <aktor>
                <imię>Bonnie</imię>
                <nazwisko>Hunt</nazwisko>
            </aktor>
            <aktor>
                <imię>Michael</imię>
                <nazwisko>Clarke Duncan</nazwisko>
            </aktor>
        </aktorzy>
        <gatunek GATUNEK="Dramat"/>
        <box_office waluta="Dolarów">286801374</box_office>
        <ograniczenie_wiekowe od_lat="od_szesnastu_lat"/>
    </film>
    <film studio = "twentieth">
        <tytuł>Ojciec chrzestny</tytuł>
        <reżyser>Francis Ford Coppola</reżyser>
        <data_premiery>1972-12-31</data_premiery>
        <aktorzy>
            <aktor>
                <imię>Marlon</imię>
                <nazwisko>Brando</nazwisko>
            </aktor>
            <aktor>
                <imię>Al</imię>
                <nazwisko>Pacino</nazwisko>
            </aktor>
            <aktor>
                <imię>James</imię>
                <nazwisko>Caan</nazwisko>
            </aktor>
            <aktor>
                <imię>Richard</imię>
                <nazwisko>Castellano</nazwisko>
            </aktor>
            <aktor>
                <imię>Robert</imię>
                <nazwisko>Duvall</nazwisko>
            </aktor>
        </aktorzy>
        <gatunek GATUNEK="Dramat"/>
        <box_office waluta="Dolarów">245066411</box_office>
        <ograniczenie_wiekowe od_lat="od_szesnastu_lat"/>
    </film>
    <film studio = "twentieth">
        <tytuł>Dwunastu gniewnych ludzi</tytuł>
        <reżyser>Sidney Lumet</reżyser>
        <data_premiery>1959-11-01</data_premiery>
        <aktorzy>
            <aktor>
                <imię>Martin</imię>
                <nazwisko>Balsam</nazwisko>
            </aktor>
            <aktor>
                <imię>John</imię>
                <nazwisko>Fiedler</nazwisko>
            </aktor>
            <aktor>
                <imię>Jack</imię>
                <nazwisko>Klugman</nazwisko>
            </aktor>
        </aktorzy>
        <gatunek GATUNEK="Dramat"/>
        <ograniczenie_wiekowe od_lat="od_trzynastu_lat"/>
    </film>
    <film studio = "twentieth">
        <tytuł>Forrest Gump</tytuł>
        <reżyser>Robert Zemeckis</reżyser>
        <data_premiery>1994-11-04</data_premiery>
        <aktorzy>
            <aktor>
                <imię>Tom</imię>
                <nazwisko>Hanks</nazwisko>
            </aktor>
            <aktor>
                <imię>Robin</imię>
                <nazwisko>Wright</nazwisko>
            </aktor>
            <aktor>
                <imię>Gary</imię>
                <nazwisko>Sinise</nazwisko>
            </aktor>
        </aktorzy>
        <gatunek GATUNEK="Dramat"/>
        <box_office waluta="Dolarów">677387716</box_office>
        <ograniczenie_wiekowe od_lat="od_trzynastu_lat"/>
    </film>
    <film studio = "PIXAR">
        <tytuł>Lot nad kukułczym gniazdem</tytuł>
        <reżyser>Miloš Forman</reżyser>
        <data_premiery>1975-12-31</data_premiery>
        <aktorzy>
            <aktor>
                <imię>Jack</imię>
                <nazwisko>Nicholson</nazwisko>
            </aktor>
            <aktor>
                <imię>Louise</imię>
                <nazwisko>Fletcher</nazwisko>
            </aktor>
            <aktor>
                <imię>Michael</imię>
                <nazwisko>Berryman</nazwisko>
            </aktor>
            <aktor>
                <imię>Danny</imię>
                <nazwisko>DeVito</nazwisko>
            </aktor>
        </aktorzy>
        <gatunek GATUNEK="Dramat"/>
        <ograniczenie_wiekowe od_lat="od_szesnastu_lat"/>
    </film>
    <film studio = "twentieth">
        <tytuł>Ojciec chrzestny II</tytuł>
        <reżyser>Francis Ford Coppola</reżyser>
        <data_premiery>1974-12-12</data_premiery>
        <aktorzy>
            <aktor>
                <imię>Al</imię>
                <nazwisko>Pacino</nazwisko>
            </aktor>
            <aktor>
                <imię>Robert</imię>
                <nazwisko>Duvall</nazwisko>
            </aktor>
            <aktor>
                <imię>Diane</imię>
                <nazwisko>Keaton</nazwisko>
            </aktor>
            <aktor>
                <imię>Robert</imię>
                <nazwisko>De Niro</nazwisko>
            </aktor>
        </aktorzy>
        <gatunek GATUNEK="Dramat"/>
        <box_office waluta="Dolarów">193000000</box_office>
        <ograniczenie_wiekowe od_lat="od_szesnastu_lat"/>
    </film>
    <film studio = "twentieth">
        <tytuł>Władca Pierścieni: Powrót króla</tytuł>
        <reżyser>Peter Jackson</reżyser>
        <data_premiery>2004-01-01</data_premiery>
        <aktorzy>
            <aktor>
                <imię>Elijah</imię>
                <nazwisko>Wood</nazwisko>
            </aktor>
            <aktor>
                <imię>Sean</imię>
                <nazwisko>Astin</nazwisko>
            </aktor>
            <aktor>
                <imię>Dominic</imię>
                <nazwisko>Monaghan</nazwisko>
            </aktor>
            <aktor>
                <imię>Billy</imię>
                <nazwisko>Boyd</nazwisko>
            </aktor>
            <aktor>
                <imię>Viggo</imię>
                <nazwisko>Mortensen</nazwisko>
            </aktor>
            <aktor>
                <imię>Ian</imię>
                <nazwisko>McKellen</nazwisko>
            </aktor>
            <aktor>
                <imię>Liv</imię>
                <nazwisko>Tyler</nazwisko>
            </aktor>
            <aktor>
                <imię>Orlando</imię>
                <nazwisko>Bloom</nazwisko>
            </aktor>
            <aktor>
                <imię>Hugo</imię>
                <nazwisko>Weaving</nazwisko>
            </aktor>
            <aktor>
                <imię>Cristopher</imię>
                <nazwisko>Lee</nazwisko>
            </aktor>
        </aktorzy>
        <gatunek GATUNEK="Fantasy"/>
        <box_office waluta="Dolarów">1119929521</box_office>
        <ograniczenie_wiekowe od_lat="od_siedmiu_lat"/>
    </film>
    <film studio = "twentieth">
        <tytuł>Lista Schindlera</tytuł>
        <reżyser>Steven Spielberg</reżyser>
        <data_premiery>1993-12-31</data_premiery>
        <aktorzy>
            <aktor>
                <imię>Liam</imię>
                <nazwisko>Neeson</nazwisko>
            </aktor>
            <aktor>
                <imię>Ben</imię>
                <nazwisko>Kingsley</nazwisko>
            </aktor>
            <aktor>
                <imię>Ralph</imię>
                <nazwisko>Fiennes</nazwisko>
            </aktor>
            <aktor>
                <imię>Caroline</imię>
                <nazwisko>Goodall</nazwisko>
            </aktor>
        </aktorzy>
        <gatunek GATUNEK="Dramat"/>
        <box_office waluta="Dolarów">321306305</box_office>
        <ograniczenie_wiekowe od_lat="od_szesnastu_lat"/>
    </film>
    <film studio = "twentieth">
        <tytuł>Pulp Fiction</tytuł>
        <reżyser>Quentin Tarantino</reżyser>
        <data_premiery>1995-05-19</data_premiery>
        <aktorzy>
            <aktor>
                <imię>John</imię>
                <nazwisko>Travolta</nazwisko>
            </aktor>
            <aktor>
                <imię>Samuel L.</imię>
                <nazwisko>Jackson</nazwisko>
            </aktor>
            <aktor>
                <imię>Uma</imię>
                <nazwisko>Thurman</nazwisko>
            </aktor>
            <aktor>
                <imię>Bruce</imię>
                <nazwisko>Willis</nazwisko>
            </aktor>
        </aktorzy>
